apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-backend-service
  namespace: paymybuddy
spec:
  selector:
    app: paymybuddy-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
