apiVersion: v1
kind: ConfigMap
metadata:
  name: paymybuddy-config
  namespace: paymybuddy
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://paymybuddy-db-service:3306/db_paymybuddy?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_JPA_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
