apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-db-service
  namespace: paymybuddy
spec:
  selector:
    app: paymybuddy-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
